### ISSUE TITLE
maximillian files

### ISSUE THREAD

**Issue by badjano** [joshuahodge/juceSynthFramework#3]
where can I find it?
Thank you for this, I am really looking forward to create my own synth

**Comment by DmitryThink** [comment]
Here https://github.com/micknoise/Maximilian
In some video tutorial, he shows which files you need.

**Comment by badjano** [comment]
I found it, forgot to close this, sorry...
now I´m having other issues, like finding the file aeffectx.h, and somehow visual studio can´t find maximilian.h although it is inside the project... I saw you are doing this on a mac, I´ll try on my mac tomorrow

**Comment by DmitryThink** [comment]
I did it on my linux =)
